# Generated by Django 4.0.5 on 2022-06-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='google_plus_link',
            field=models.URLField(max_length=100),
        ),
    ]
