# Generated by Django 4.0.5 on 2022-06-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_teammodel_google_plus_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammodel',
            old_name='potos',
            new_name='photos',
        ),
    ]
